version: '3'
services:
    web:
        build: .
        image: app
        command: python manage.py runserver 0.0.0.0:8000
        volumes: 
            - ./:/usr/src/app
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on: 
            - redis_db
    redis_db:
        image: redis:6.2.4
        container_name: redis_db
        expose: 
            - 6379
    worker:
        build: .
        image: app
        command: celery -A uploadcsv worker -l info
        volumes: 
            - ./:/usr/src/app
        depends_on: 
            - redis_db
            - web
        env_file:
            - ./.env.dev

            